// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    rutinas,
    entrenamientos,
    catalogoEjercicios,
    ejercicios,
    serie,
    idxCatalogoBusqueda,
    idxCatalogoBodyPart,
    idxCatalogoEquipment,
  ];
  late final Shape0 rutinas = Shape0(
    source: i0.VersionedTable(
      entityName: 'rutinas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 entrenamientos = Shape1(
    source: i0.VersionedTable(
      entityName: 'entrenamientos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 catalogoEjercicios = Shape2(
    source: i0.VersionedTable(
      entityName: 'catalogo_ejercicios',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 ejercicios = Shape3(
    source: i0.VersionedTable(
      entityName: 'ejercicios',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_3, _column_16, _column_6, _column_17],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 serie = Shape4(
    source: i0.VersionedTable(
      entityName: 'serie',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxCatalogoBusqueda = i1.Index(
    'idx_catalogo_busqueda',
    'CREATE INDEX idx_catalogo_busqueda ON catalogo_ejercicios (busqueda)',
  );
  final i1.Index idxCatalogoBodyPart = i1.Index(
    'idx_catalogo_body_part',
    'CREATE INDEX idx_catalogo_body_part ON catalogo_ejercicios (body_part)',
  );
  final i1.Index idxCatalogoEquipment = i1.Index(
    'idx_catalogo_equipment',
    'CREATE INDEX idx_catalogo_equipment ON catalogo_ejercicios (equipment)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get nombre =>
      columnsByName['nombre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get color =>
      columnsByName['color']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'nombre',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'color',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get idRutina =>
      columnsByName['id_rutina']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fecha =>
      columnsByName['fecha']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id_rutina',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES rutinas(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fecha',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nombre =>
      columnsByName['nombre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bodyPart =>
      columnsByName['body_part']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get equipment =>
      columnsByName['equipment']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get target =>
      columnsByName['target']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get muscleGroup =>
      columnsByName['muscle_group']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get secondaryMuscles =>
      columnsByName['secondary_muscles']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get instrucciones =>
      columnsByName['instrucciones']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get image =>
      columnsByName['image']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get gif =>
      columnsByName['gif']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get busqueda =>
      columnsByName['busqueda']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'nombre',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'body_part',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'equipment',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'target',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'muscle_group',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'secondary_muscles',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'instrucciones',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'image',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'gif',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'busqueda',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get idRutina =>
      columnsByName['id_rutina']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get idCatalogo =>
      columnsByName['id_catalogo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nombre =>
      columnsByName['nombre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get descripcion =>
      columnsByName['descripcion']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id_catalogo',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES catalogo_ejercicios(id)',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'descripcion',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get idEntrenamiento =>
      columnsByName['id_entrenamiento']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get idEjercicio =>
      columnsByName['id_ejercicio']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nSerie =>
      columnsByName['n_serie']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get repeticiones =>
      columnsByName['repeticiones']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get peso =>
      columnsByName['peso']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get calentamiento =>
      columnsByName['calentamiento']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id_entrenamiento',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES entrenamientos(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id_ejercicio',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES ejercicios(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'n_serie',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'repeticiones',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_22(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'peso',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'calentamiento',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (calentamiento IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    rutinas,
    entrenamientos,
    catalogoEjercicios,
    ejercicios,
    serie,
    idxCatalogoBusqueda,
    idxCatalogoBodyPart,
    idxCatalogoEquipment,
  ];
  late final Shape0 rutinas = Shape0(
    source: i0.VersionedTable(
      entityName: 'rutinas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 entrenamientos = Shape1(
    source: i0.VersionedTable(
      entityName: 'entrenamientos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 catalogoEjercicios = Shape2(
    source: i0.VersionedTable(
      entityName: 'catalogo_ejercicios',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 ejercicios = Shape5(
    source: i0.VersionedTable(
      entityName: 'ejercicios',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_3,
        _column_16,
        _column_6,
        _column_17,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 serie = Shape4(
    source: i0.VersionedTable(
      entityName: 'serie',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxCatalogoBusqueda = i1.Index(
    'idx_catalogo_busqueda',
    'CREATE INDEX idx_catalogo_busqueda ON catalogo_ejercicios (busqueda)',
  );
  final i1.Index idxCatalogoBodyPart = i1.Index(
    'idx_catalogo_body_part',
    'CREATE INDEX idx_catalogo_body_part ON catalogo_ejercicios (body_part)',
  );
  final i1.Index idxCatalogoEquipment = i1.Index(
    'idx_catalogo_equipment',
    'CREATE INDEX idx_catalogo_equipment ON catalogo_ejercicios (equipment)',
  );
}

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get idRutina =>
      columnsByName['id_rutina']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get idCatalogo =>
      columnsByName['id_catalogo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nombre =>
      columnsByName['nombre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get descripcion =>
      columnsByName['descripcion']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get orden =>
      columnsByName['orden']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'orden',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    rutinas,
    entrenamientos,
    catalogoEjercicios,
    ejercicios,
    serie,
    ajustes,
    idxCatalogoBusqueda,
    idxCatalogoBodyPart,
    idxCatalogoEquipment,
  ];
  late final Shape0 rutinas = Shape0(
    source: i0.VersionedTable(
      entityName: 'rutinas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 entrenamientos = Shape6(
    source: i0.VersionedTable(
      entityName: 'entrenamientos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_3, _column_4, _column_25],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 catalogoEjercicios = Shape2(
    source: i0.VersionedTable(
      entityName: 'catalogo_ejercicios',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 ejercicios = Shape5(
    source: i0.VersionedTable(
      entityName: 'ejercicios',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_3,
        _column_16,
        _column_6,
        _column_17,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 serie = Shape7(
    source: i0.VersionedTable(
      entityName: 'serie',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_26,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 ajustes = Shape8(
    source: i0.VersionedTable(
      entityName: 'ajustes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(clave)'],
      columns: [_column_27, _column_28],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxCatalogoBusqueda = i1.Index(
    'idx_catalogo_busqueda',
    'CREATE INDEX idx_catalogo_busqueda ON catalogo_ejercicios (busqueda)',
  );
  final i1.Index idxCatalogoBodyPart = i1.Index(
    'idx_catalogo_body_part',
    'CREATE INDEX idx_catalogo_body_part ON catalogo_ejercicios (body_part)',
  );
  final i1.Index idxCatalogoEquipment = i1.Index(
    'idx_catalogo_equipment',
    'CREATE INDEX idx_catalogo_equipment ON catalogo_ejercicios (equipment)',
  );
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get idRutina =>
      columnsByName['id_rutina']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fecha =>
      columnsByName['fecha']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get nota =>
      columnsByName['nota']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'nota',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get idEntrenamiento =>
      columnsByName['id_entrenamiento']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get idEjercicio =>
      columnsByName['id_ejercicio']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nSerie =>
      columnsByName['n_serie']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get repeticiones =>
      columnsByName['repeticiones']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get peso =>
      columnsByName['peso']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get calentamiento =>
      columnsByName['calentamiento']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get rpe =>
      columnsByName['rpe']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get nota =>
      columnsByName['nota']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<double> _column_26(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'rpe',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get clave =>
      columnsByName['clave']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get valor =>
      columnsByName['valor']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'clave',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'valor',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    rutinas,
    entrenamientos,
    catalogoEjercicios,
    ejercicios,
    serie,
    ajustes,
    sesionesActivas,
    idxCatalogoBusqueda,
    idxCatalogoBodyPart,
    idxCatalogoEquipment,
  ];
  late final Shape0 rutinas = Shape0(
    source: i0.VersionedTable(
      entityName: 'rutinas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 entrenamientos = Shape9(
    source: i0.VersionedTable(
      entityName: 'entrenamientos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_3, _column_4, _column_25, _column_29],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 catalogoEjercicios = Shape2(
    source: i0.VersionedTable(
      entityName: 'catalogo_ejercicios',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 ejercicios = Shape10(
    source: i0.VersionedTable(
      entityName: 'ejercicios',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_3,
        _column_16,
        _column_6,
        _column_17,
        _column_24,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 serie = Shape7(
    source: i0.VersionedTable(
      entityName: 'serie',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_26,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 ajustes = Shape8(
    source: i0.VersionedTable(
      entityName: 'ajustes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(clave)'],
      columns: [_column_27, _column_28],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 sesionesActivas = Shape11(
    source: i0.VersionedTable(
      entityName: 'sesiones_activas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_3, _column_31, _column_32, _column_33],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxCatalogoBusqueda = i1.Index(
    'idx_catalogo_busqueda',
    'CREATE INDEX idx_catalogo_busqueda ON catalogo_ejercicios (busqueda)',
  );
  final i1.Index idxCatalogoBodyPart = i1.Index(
    'idx_catalogo_body_part',
    'CREATE INDEX idx_catalogo_body_part ON catalogo_ejercicios (body_part)',
  );
  final i1.Index idxCatalogoEquipment = i1.Index(
    'idx_catalogo_equipment',
    'CREATE INDEX idx_catalogo_equipment ON catalogo_ejercicios (equipment)',
  );
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get idRutina =>
      columnsByName['id_rutina']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fecha =>
      columnsByName['fecha']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get nota =>
      columnsByName['nota']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get duracionSeg =>
      columnsByName['duracion_seg']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duracion_seg',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get idRutina =>
      columnsByName['id_rutina']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get idCatalogo =>
      columnsByName['id_catalogo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nombre =>
      columnsByName['nombre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get descripcion =>
      columnsByName['descripcion']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get orden =>
      columnsByName['orden']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get descansoSeg =>
      columnsByName['descanso_seg']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'descanso_seg',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get idRutina =>
      columnsByName['id_rutina']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get inicio =>
      columnsByName['inicio']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get actualizado =>
      columnsByName['actualizado']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get estado =>
      columnsByName['estado']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'inicio',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'actualizado',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'estado',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    rutinas,
    entrenamientos,
    catalogoEjercicios,
    ejercicios,
    serie,
    ajustes,
    sesionesActivas,
    favoritos,
    vistos,
    medidas,
    idxCatalogoBusqueda,
    idxCatalogoBodyPart,
    idxCatalogoEquipment,
    idxCatalogoTarget,
  ];
  late final Shape0 rutinas = Shape0(
    source: i0.VersionedTable(
      entityName: 'rutinas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 entrenamientos = Shape9(
    source: i0.VersionedTable(
      entityName: 'entrenamientos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_3, _column_4, _column_25, _column_29],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 catalogoEjercicios = Shape2(
    source: i0.VersionedTable(
      entityName: 'catalogo_ejercicios',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 ejercicios = Shape10(
    source: i0.VersionedTable(
      entityName: 'ejercicios',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_3,
        _column_16,
        _column_6,
        _column_17,
        _column_24,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 serie = Shape7(
    source: i0.VersionedTable(
      entityName: 'serie',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_26,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 ajustes = Shape8(
    source: i0.VersionedTable(
      entityName: 'ajustes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(clave)'],
      columns: [_column_27, _column_28],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 sesionesActivas = Shape11(
    source: i0.VersionedTable(
      entityName: 'sesiones_activas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_3, _column_31, _column_32, _column_33],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 favoritos = Shape12(
    source: i0.VersionedTable(
      entityName: 'favoritos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id_catalogo)'],
      columns: [_column_34, _column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 vistos = Shape13(
    source: i0.VersionedTable(
      entityName: 'vistos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id_catalogo)'],
      columns: [_column_34, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 medidas = Shape14(
    source: i0.VersionedTable(
      entityName: 'medidas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(fecha, tipo)'],
      columns: [_column_0, _column_4, _column_36, _column_37],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxCatalogoBusqueda = i1.Index(
    'idx_catalogo_busqueda',
    'CREATE INDEX idx_catalogo_busqueda ON catalogo_ejercicios (busqueda)',
  );
  final i1.Index idxCatalogoBodyPart = i1.Index(
    'idx_catalogo_body_part',
    'CREATE INDEX idx_catalogo_body_part ON catalogo_ejercicios (body_part)',
  );
  final i1.Index idxCatalogoEquipment = i1.Index(
    'idx_catalogo_equipment',
    'CREATE INDEX idx_catalogo_equipment ON catalogo_ejercicios (equipment)',
  );
  final i1.Index idxCatalogoTarget = i1.Index(
    'idx_catalogo_target',
    'CREATE INDEX idx_catalogo_target ON catalogo_ejercicios (target)',
  );
}

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get idCatalogo =>
      columnsByName['id_catalogo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get creado =>
      columnsByName['creado']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id_catalogo',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'creado',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get idCatalogo =>
      columnsByName['id_catalogo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get fecha =>
      columnsByName['fecha']! as i1.GeneratedColumn<int>;
}

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fecha =>
      columnsByName['fecha']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get tipo =>
      columnsByName['tipo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get valor =>
      columnsByName['valor']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tipo',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_37(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'valor',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );

final class Schema7 extends i0.VersionedSchema {
  Schema7({required super.database}) : super(version: 7);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    rutinas,
    entrenamientos,
    catalogoEjercicios,
    ejercicios,
    serie,
    ajustes,
    sesionesActivas,
    favoritos,
    vistos,
    medidas,
    idxCatalogoBusqueda,
    idxCatalogoBodyPart,
    idxCatalogoEquipment,
    idxCatalogoTarget,
  ];
  late final Shape0 rutinas = Shape0(
    source: i0.VersionedTable(
      entityName: 'rutinas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 entrenamientos = Shape9(
    source: i0.VersionedTable(
      entityName: 'entrenamientos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_3, _column_4, _column_25, _column_29],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 catalogoEjercicios = Shape2(
    source: i0.VersionedTable(
      entityName: 'catalogo_ejercicios',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 ejercicios = Shape15(
    source: i0.VersionedTable(
      entityName: 'ejercicios',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_3,
        _column_16,
        _column_6,
        _column_17,
        _column_24,
        _column_30,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 serie = Shape7(
    source: i0.VersionedTable(
      entityName: 'serie',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_26,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 ajustes = Shape8(
    source: i0.VersionedTable(
      entityName: 'ajustes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(clave)'],
      columns: [_column_27, _column_28],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 sesionesActivas = Shape11(
    source: i0.VersionedTable(
      entityName: 'sesiones_activas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_3, _column_31, _column_32, _column_33],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 favoritos = Shape12(
    source: i0.VersionedTable(
      entityName: 'favoritos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id_catalogo)'],
      columns: [_column_34, _column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 vistos = Shape13(
    source: i0.VersionedTable(
      entityName: 'vistos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id_catalogo)'],
      columns: [_column_34, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 medidas = Shape14(
    source: i0.VersionedTable(
      entityName: 'medidas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(fecha, tipo)'],
      columns: [_column_0, _column_4, _column_36, _column_37],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxCatalogoBusqueda = i1.Index(
    'idx_catalogo_busqueda',
    'CREATE INDEX idx_catalogo_busqueda ON catalogo_ejercicios (busqueda)',
  );
  final i1.Index idxCatalogoBodyPart = i1.Index(
    'idx_catalogo_body_part',
    'CREATE INDEX idx_catalogo_body_part ON catalogo_ejercicios (body_part)',
  );
  final i1.Index idxCatalogoEquipment = i1.Index(
    'idx_catalogo_equipment',
    'CREATE INDEX idx_catalogo_equipment ON catalogo_ejercicios (equipment)',
  );
  final i1.Index idxCatalogoTarget = i1.Index(
    'idx_catalogo_target',
    'CREATE INDEX idx_catalogo_target ON catalogo_ejercicios (target)',
  );
}

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get idRutina =>
      columnsByName['id_rutina']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get idCatalogo =>
      columnsByName['id_catalogo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nombre =>
      columnsByName['nombre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get descripcion =>
      columnsByName['descripcion']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get orden =>
      columnsByName['orden']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get descansoSeg =>
      columnsByName['descanso_seg']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get repMin =>
      columnsByName['rep_min']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get repMax =>
      columnsByName['rep_max']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get incrementoKg =>
      columnsByName['incremento_kg']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get estrategia =>
      columnsByName['estrategia']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'rep_min',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'rep_max',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_40(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'incremento_kg',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'estrategia',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      case 6:
        final schema = Schema7(database: database);
        final migrator = i1.Migrator(database, schema);
        await from6To7(migrator, schema);
        return 7;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
    from5To6: from5To6,
    from6To7: from6To7,
  ),
);
